sudo: false
script:
- ./build.sh
deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: target/Melanoid.jar
  skip_cleanup: true
  on:
    tags: true
env:
  global:
  - secure: jju3kpnHt2DzMD9rbUKMsNdoCa1uWJfmJRtsKBd56hrL1Ju3mJ/zzoPs+Vp0t+peqRBMRB35cZtjSa5zbwSKHma9Ywfwq5lFPkQjk6mNh9Z7g3Umq117LZX+enDeTlHvnuM5iskgUOi5k6FYMFamrl+QcAbuTg5B96I8EiMyzPWy5Hz+0kb/hfxgqWXm/OYwCTOR3k3552/ubO+v/0M+c9yuag0kBdiP1ebWMMEfZ5cOqLNVNPy9JBA3bYcPipytBU0eh1ZB724OHK2hHP7T5H8RNrxAzmofAPLfswEY8/nP07r53UdQHIDNs6iN31OHyy7BcurAk/KtlXpWfBJSeJmBbQi/5OGTvsz+h2/g8zLH/lrYUTI3lxrF8XT9Io+KxhfGMlWP3JugcAo2dZDr/bS6S/Qy4a51z9rvX0zAxHye+O/+4L401OeKYltm7iJD/Ua/SdtPXARNibH1Lz+cdmTm9uqhimAxCxzVAQGRKuNK1W8G37lvPw1DcYJ0CUGZaFyFQKMlPmqMqQ2i/3PvbtJOG4ljPIUcfdY8UZiLgbf9Xlaz6V9qVJYN7pogU6GK+jvaE6XDakp4ZW7OZhSsrt/Xugwe/oitoM3cwuCBRvRQJXgyLNx/SklWQ6q5CB6gOJO31qUtlJVs60WzHJB/S1UcSTdiWsldX1f9NFAxmn0=
